{
 "title": "Postgres_Overview",
 "tags": [ "postgres" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(pg_settings_array_nulls,instance)"
    }
   },
   {
    "name": "datname",
    "label": "database",
    "query": {
     "query": "label_values(pg_locks_count,datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active session",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$host.+\", state=\"active\"} "
    }
   ]
  },
  {
   "title": "Xact rollback",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=~\"$host.+\"}[1m]))by(database)"
    }
   ]
  },
  {
   "title": "Temp file counters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_temp_files{datname=~\"$datname\", instance=~\"$host.+\"})by(database)"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$host.+\"})"
    }
   ]
  },
  {
   "title": "Statements max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_pg_stat_statements_max{instance=~\"$host.+\"}"
    }
   ]
  },
  {
   "title": "Xact commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=~\"$host.+\"}[1m]))by(database)"
    }
   ]
  },
  {
   "title": "Current fetch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$host.+\"})"
    }
   ]
  },
  {
   "title": "Temp bytes counters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_temp_bytes{datname=~\"$datname\", instance=~\"$host.+\"})by(database)"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$host.+\"})"
    }
   ]
  },
  {
   "title": "Average  request time for the last minute to database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_exec_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Average  request time for the last minute to instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_mean_exec_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (server)  ",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Count request  to database for the last minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_statements_calls{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 Most called request to database",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "topk(20,increase(pg_stat_statements_calls{datname=~\"$datname\", instance=~\"$host.+\"}[10m]))"
      }
     ]
    },
    {
     "title": "Top 20 Most long request time to database",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(20,increase(pg_stat_statements_mean_exec_time{datname=~\"$datname\", instance=~\"$host.+\"}[10m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$host.+\", state=\"active\"} ",
       "legendFormat": "{{instance}},{{datname}},state : {{state}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$host.+\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{instance}},{{datname}},state : {{state}}"
      }
     ]
    },
    {
     "title": "Numbackends",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{datname=~\"$datname\", instance=~\"$host.+\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock tables",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$host.+\"} ",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_deadlocks{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Max TX duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration{datname=~\"$datname\", instance=~\"$host.+\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_conflicts_confl_deadlock{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}} deadlock"
      },
      {
       "expr": "rate(pg_stat_database_conflicts{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "rate(pg_stat_database_conflicts_confl_bufferpin{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}} bufferpin"
      },
      {
       "expr": "rate(pg_stat_database_conflicts_confl_snapshot{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}} shaphot"
      },
      {
       "expr": "rate(pg_stat_database_conflicts_confl_tablespace{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}} tablespace"
      }
     ]
    }
   ]
  },
  {
   "title": "Planning the statement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total rows retrieved or affected by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_rows{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Maximum time spent planning the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_max_plan_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total time spent planning the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_total_plan_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Minimum time spent planning the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_min_plan_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Deviation of time spent executing the statement, in millisecond",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_stddev_exec_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Mean time spent planning the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_mean_plan_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Deviation of time spent planning the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_stddev_plan_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname,instance)  ",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements block ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of shared block cache hits by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_shared_blks_hit{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks read by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_shared_blks_read{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local block cache hits by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_local_blks_hit{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks dirtied by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of shared blocks written by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_shared_blks_written{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total time the statement spent writing blocks, in milliseconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_blk_write_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local blocks read by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_local_blks_read{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of local blocks dirtied by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_local_blks_dirtied{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks read by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_temp_blks_read{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks written by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_temp_blks_written{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of WAL full page images generated by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_wal_bytes{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of WAL full page images generated by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_wal_fpi{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of WAL records generated by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_wal_records{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Total number of temp blocks written by the statement",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_statements_temp_blks_written{datname=~\"$datname\", instance=~\"$host.+\"}[1m])) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$host.+\"} != 0",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$host.+\"}",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$host.+\"} ",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$host.+\"}",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$host.+\"} ",
       "legendFormat": "{{instance}}, {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blk hits/read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_blks_hit{datname=~\"$datname\", instance=~\"$host.+\"}[30s]))by(database)",
       "legendFormat": "Hits"
      },
      {
       "expr": "sum(rate(pg_stat_database_blks_read{datname=~\"$datname\", instance=~\"$host.+\"}[30s]))by(database)",
       "legendFormat": "Reads"
      }
     ]
    },
    {
     "title": "Blk read/whrite time - rate 1m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$datname\", instance=~\"$host.+\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  }
 ]
}