{
 "title": "Go metrics",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutines,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "rate(process_virtual_memory_bytes{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "rate(go_memstats_heap_inuse_bytes{job=\"$job\"}[30s])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_open_fds{job=\"$job\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}